### ISSUE TITLE
Switchable Mapillary coverage layer

### ISSUE THREAD

**Issue by pratikyadav** [k1wiosm/checkautopista2#10]
_This is a feature request._

The presence of mapillary imagery make it quite easy to map signboards.  It would be very helpful to have a switchable layer of mapillary coverage in checkautopista2.

TMS layer-> `https://d2munx5tg0hw47.cloudfront.net/tiles/{z}/{x}/{y}.mapbox` 
Mapillary blog-> http://blog.mapillary.com/update/2015/05/27/vectortiles.html

**Comment by k1wiosm** [comment]
I have been thinking about this. 

I think it would be nice to have a mapillary layer, however I don't know how to do it right. The paths showing the mapillary coverage would conflict with the current lines of the freeways showing lanes and maxspeed tagging. 

Do you have any suggestion?

**Comment by pratikyadav** [comment]
My suggestion-
4 layer
- bottom base map (without highway)
- middle layer: Mapillary (with a switch to turn on/off in right top corner)
- top layer: highways with label
- downloaded layer on top showing lanes and max speed

How does this sound? make sense or will make the map look too messy?

**Comment by k1wiosm** [comment]
I added a Mapillary coverage layer (https://github.com/k1wiosm/checkautopista2/commit/fb04475f024fe24079d89b8fd54997aac02f0934). You have to enable it from the settings panel. Let me know what you think.

![](https://cloud.githubusercontent.com/assets/8932566/14927100/408d55fa-0e50-11e6-995e-e1cba93ef724.png)

**Comment by planemad** [comment]
@k1wiosm 👍 👍 so awesome!

**Comment by planemad** [comment]
There's a big push to update exit numbers and destination from Mapillary in the top 30 US cities https://github.com/mapbox/mapping/issues/178 .

The mappers currently use [this reference map](https://api.mapbox.com/styles/v1/planemad/cijwpzx4m00ofcakw1m0f1ir1.html?title=true&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#10.21/38.78017924398682/-75.12647865217716/0) in JOSM to work in the focus area. 

@k1wiosm would be great to just have the city boundaries as a layer in autpista so that it is convenient to map. What would be the best way to do this?

This is the JOSM tms currently being used: `tms:https://api.mapbox.com/styles/v1/planemad/cijwpzx4m00ofcakw1m0f1ir1/tiles/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ`

**Comment by k1wiosm** [comment]
I have been looking into that city boundaries layer.

I keep getting `{"message":"Not Found"}` when using that tms that you said. However, inspecting the previous map that you send I managed to extract this layer: `https://b.tiles.mapbox.com/v4/planemad.ca2zzwvk/{z}/{x}/{y}.vector.pbf?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ`, and that one is working. Is that the one you want?

**Comment by planemad** [comment]
@k1wiosm woops, had a .png there by mistake. Updated the url now. The vector.pbf is the raw data, not the rendered map.

**Comment by k1wiosm** [comment]
I see. Let me try with that one then.

**Comment by k1wiosm** [comment]
That layer includes satellite image, freeways and city boundaries. Everything together. Is that what you want? 

![](https://cloud.githubusercontent.com/assets/8932566/15058009/16e26dfc-131a-11e6-81d9-a87def12796e.png)

**Comment by planemad** [comment]
@k1wiosm 👍 this works. Can fine tune the style based on feedback as it comes in.

**Comment by k1wiosm** [comment]
Added on https://github.com/k1wiosm/checkautopista2/commit/192d00aa90fa16c1d0141f7a618c257abc0bc3e9. Let me know what you think. Is the layer name all right?

**Comment by planemad** [comment]
Thank you @k1wiosm if you have any ideas to improve the style, let me know.

**Comment by k1wiosm** [comment]
@planemad, I would like it better if the layer didn't include the satellite image. Does that work with you?

**Comment by planemad** [comment]
👍 @k1wiosm. Its one of the limitations of rasterized GL styles that it does not support transparent pngs currently. Removing satellite would make the background black :|

The only way to get a clean result is to migrate the entire map to [GL](https://www.mapbox.com/mapbox-gl-js/api/). This might be a bit of a lift to migrate but might work out better in the long run.

**Comment by k1wiosm** [comment]
For the time being, I'm going to stick with Leaflet. However I can work with any raw vector tiles supported by [Leaflet.VectorGrid](https://github.com/IvanSanchez/Leaflet.VectorGrid), as I used that for the Mapillary vector tiles. Since it is simple data (city boundaries), I would only have to apply some colour (as I did to the Mapillary data) and that's it. What do you think?
