### ISSUE TITLE
Unused data queried by Overpass

### ISSUE THREAD

**Issue by gileri** [k1wiosm/checkautopista2#3]
The Overpass query used to get a single relation's data store unused data in the 'x' set in [getdata.js](https://github.com/k1wiosm/checkautopista2/blob/master/js/getdata.js#L183)

**Comment by k1wiosm** [comment]
I don't think there is a problem here, but thank you for looking at the code.

I am putting the service area nodes into `x` to prevent the next statement (`way(around:1000)["highway"~"services|rest_area"];`) from searching around the service area nodes instead of the freeway nodes as intended. This data is not unused as it is inside a parenthesis which acts as an OR.
It's easier to see it when properly indented:

    [out:json][timeout:'+timeout+'];
    relation('+this.relID+');
    way(r);
    node(w);
    ( 
      node(around:500)["highway"~"services|rest_area"]->.x;
      way(around:1000)["highway"~"services|rest_area"];
    );
    (
      ._;
      >;
    );
    out center qt;

**Comment by gileri** [comment]
My bad, after reading again the [Overpass QL wiki page](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Union), you are right.

> [The union] result set is the union of the result sets of all sub-statements, regardless of whether a sub-statement has a redirected result set or not.

Sorry for the trouble.
